### ISSUE TITLE
Problem with android 7 permission

### ISSUE THREAD

**Issue by djamb** [Arksine/AutoIntegrate#1]
I think that Android 7 have other usb permission protocol for USB, try CameraActivity

com.arksine.autointegrate E/HardwareReceiver: Error trying to assign automatic usb permission : /dev/bus/usb/001/002

**Comment by Arksine** [comment]
I'm not even close to an initial release, but I should probably change that error to a warning.   The app won't assign automatic USB permissions unless its either installed as a system app or signed with the ROM's private keys.  When automatic permission is denied defaults back to requesting permission from the user via Android's popup.

FWIW, the camera functionality wont work on Nougat because it denies access to libuvc/libusb.   If camera functionality is all you want then there is an app on the appstore called UsbWebCamera that should work.

The rest of it should work fine on Nougat  when its finished, and I might try to address camera functionality on Nougat later.
